export const mockUsers = [
  {
    firstName: 'TestEmployee1',
    lastName: 'One',
    startDate: '01/01/2020',
    department: 'Human Resources',
    dob: '31/01/2000',
    street: 'Bstreet',
    city: 'Asity',
    state: 'B',
    zipCode: '02'
  },
  {
    firstName: 'TestEmployee2',
    lastName: 'Two',
    startDate: '15/03/2021',
    department: 'Sales',
    dob: '12/06/1998',
    street: 'Cstreet',
    city: 'Bcity',
    state: 'C',
    zipCode: '03'
  },
  {
    firstName: 'TestEmployee3',
    lastName: 'Three',
    startDate: '22/07/2019',
    department: 'Marketing',
    dob: '23/11/1995',
    street: 'Dstreet',
    city: 'Ccity',
    state: 'D',
    zipCode: '04'
  },
  {
    firstName: 'TestEmployee4',
    lastName: 'Four',
    startDate: '30/08/2018',
    department: 'Engineering',
    dob: '14/02/1997',
    street: 'Estreet',
    city: 'Dcity',
    state: 'E',
    zipCode: '05'
  },
  {
    firstName: 'TestEmployee5',
    lastName: 'Five',
    startDate: '05/12/2022',
    department: 'Legal',
    dob: '10/09/1999',
    street: 'Fstreet',
    city: 'Ecity',
    state: 'F',
    zipCode: '06'
  },
  {
    firstName: '0TestEmployee1',
    lastName: 'One',
    startDate: '01/01/2020',
    department: 'Human Resources',
    dob: '31/01/2000',
    street: 'Bstreet',
    city: 'Asity',
    state: 'B',
    zipCode: '02'
  },
  {
    firstName: '0TestEmployee2',
    lastName: 'Two',
    startDate: '15/03/2021',
    department: 'Sales',
    dob: '12/06/1998',
    street: 'Cstreet',
    city: 'Bcity',
    state: 'C',
    zipCode: '03'
  },
  {
    firstName: '0TestEmployee3',
    lastName: 'Three',
    startDate: '22/07/2019',
    department: 'Marketing',
    dob: '23/11/1995',
    street: 'Dstreet',
    city: 'Ccity',
    state: 'D',
    zipCode: '04'
  },
  {
    firstName: '0TestEmployee4',
    lastName: 'Four',
    startDate: '30/08/2018',
    department: 'Engineering',
    dob: '14/02/1997',
    street: 'Estreet',
    city: 'Dcity',
    state: 'E',
    zipCode: '05'
  },
  {
    firstName: '0TestEmployee5',
    lastName: 'Five',
    startDate: '05/12/2022',
    department: 'Legal',
    dob: '10/09/1999',
    street: 'Fstreet',
    city: 'Ecity',
    state: 'F',
    zipCode: '06'
  },
  {
    firstName: '3TestEmployee1',
    lastName: 'One',
    startDate: '01/01/2020',
    department: 'Human Resources',
    dob: '31/01/2000',
    street: 'Bstreet',
    city: 'Asity',
    state: 'B',
    zipCode: '02'
  },
  {
    firstName: '3TestEmployee2',
    lastName: 'Two',
    startDate: '15/03/2021',
    department: 'Sales',
    dob: '12/06/1998',
    street: 'Cstreet',
    city: 'Bcity',
    state: 'C',
    zipCode: '03'
  },
  {
    firstName: '3TestEmployee3',
    lastName: 'Three',
    startDate: '22/07/2019',
    department: 'Marketing',
    dob: '23/11/1995',
    street: 'Dstreet',
    city: 'Ccity',
    state: 'D',
    zipCode: '04'
  },
  {
    firstName: '3TestEmployee4',
    lastName: 'Four',
    startDate: '30/08/2018',
    department: 'Engineering',
    dob: '14/02/1997',
    street: 'Estreet',
    city: 'Dcity',
    state: 'E',
    zipCode: '05'
  },
  {
    firstName: '3TestEmployee5',
    lastName: 'Five',
    startDate: '05/12/2022',
    department: 'Legal',
    dob: '10/09/1999',
    street: 'Fstreet',
    city: 'Ecity',
    state: 'F',
    zipCode: '06'
  },
  {
    firstName: '2TestEmployee1',
    lastName: 'One',
    startDate: '01/01/2020',
    department: 'Human Resources',
    dob: '31/01/2000',
    street: 'Bstreet',
    city: 'Asity',
    state: 'B',
    zipCode: '02'
  },
  {
    firstName: '2TestEmployee2',
    lastName: 'Two',
    startDate: '15/03/2021',
    department: 'Sales',
    dob: '12/06/1998',
    street: 'Cstreet',
    city: 'Bcity',
    state: 'C',
    zipCode: '03'
  },
  {
    firstName: '2TestEmployee3',
    lastName: 'Three',
    startDate: '22/07/2019',
    department: 'Marketing',
    dob: '23/11/1995',
    street: 'Dstreet',
    city: 'Ccity',
    state: 'D',
    zipCode: '04'
  },
  {
    firstName: '2TestEmployee4',
    lastName: 'Four',
    startDate: '30/08/2018',
    department: 'Engineering',
    dob: '14/02/1997',
    street: 'Estreet',
    city: 'Dcity',
    state: 'E',
    zipCode: '05'
  },
  {
    firstName: '2TestEmployee5',
    lastName: 'Five',
    startDate: '05/12/2022',
    department: 'Legal',
    dob: '10/09/1999',
    street: 'Fstreet',
    city: 'Ecity',
    state: 'F',
    zipCode: '06'
  },
  {
    firstName: 'TestEmployee1',
    lastName: 'One',
    startDate: '01/01/2020',
    department: 'Human Resources',
    dob: '31/01/2000',
    street: 'Bstreet',
    city: 'Asity',
    state: 'B',
    zipCode: '02'
  },
  {
    firstName: 'TestEmployee2',
    lastName: 'Two',
    startDate: '15/03/2021',
    department: 'Sales',
    dob: '12/06/1998',
    street: 'Cstreet',
    city: 'Bcity',
    state: 'C',
    zipCode: '03'
  },
  {
    firstName: 'TestEmployee3',
    lastName: 'Three',
    startDate: '22/07/2019',
    department: 'Marketing',
    dob: '23/11/1995',
    street: 'Dstreet',
    city: 'Ccity',
    state: 'D',
    zipCode: '04'
  },
  {
    firstName: 'TestEmployee4',
    lastName: 'Four',
    startDate: '30/08/2018',
    department: 'Engineering',
    dob: '14/02/1997',
    street: 'Estreet',
    city: 'Dcity',
    state: 'E',
    zipCode: '05'
  },
  {
    firstName: 'TestEmployee5',
    lastName: 'Five',
    startDate: '05/12/2022',
    department: 'Legal',
    dob: '10/09/1999',
    street: 'Fstreet',
    city: 'Ecity',
    state: 'F',
    zipCode: '06'
  },{
    firstName: 'TestEmployee1',
    lastName: 'One',
    startDate: '01/01/2020',
    department: 'Human Resources',
    dob: '31/01/2000',
    street: 'Bstreet',
    city: 'Asity',
    state: 'B',
    zipCode: '02'
  },
  {
    firstName: 'TestEmployee2',
    lastName: 'Two',
    startDate: '15/03/2021',
    department: 'Sales',
    dob: '12/06/1998',
    street: 'Cstreet',
    city: 'Bcity',
    state: 'C',
    zipCode: '03'
  },
  {
    firstName: 'TestEmployee3',
    lastName: 'Three',
    startDate: '22/07/2019',
    department: 'Marketing',
    dob: '23/11/1995',
    street: 'Dstreet',
    city: 'Ccity',
    state: 'D',
    zipCode: '04'
  },
  {
    firstName: 'TestEmployee4',
    lastName: 'Four',
    startDate: '30/08/2018',
    department: 'Engineering',
    dob: '14/02/1997',
    street: 'Estreet',
    city: 'Dcity',
    state: 'E',
    zipCode: '05'
  },
  {
    firstName: 'TestEmployee5',
    lastName: 'Five',
    startDate: '05/12/2022',
    department: 'Legal',
    dob: '10/09/1999',
    street: 'Fstreet',
    city: 'Ecity',
    state: 'F',
    zipCode: '06'
  },{
    firstName: 'TestEmployee1',
    lastName: 'One',
    startDate: '01/01/2020',
    department: 'Human Resources',
    dob: '31/01/2000',
    street: 'Bstreet',
    city: 'Asity',
    state: 'B',
    zipCode: '02'
  },
  {
    firstName: 'TestEmployee2',
    lastName: 'Two',
    startDate: '15/03/2021',
    department: 'Sales',
    dob: '12/06/1998',
    street: 'Cstreet',
    city: 'Bcity',
    state: 'C',
    zipCode: '03'
  },
  {
    firstName: 'TestEmployee3',
    lastName: 'Three',
    startDate: '22/07/2019',
    department: 'Marketing',
    dob: '23/11/1995',
    street: 'Dstreet',
    city: 'Ccity',
    state: 'D',
    zipCode: '04'
  },
  {
    firstName: 'TestEmployee4',
    lastName: 'Four',
    startDate: '30/08/2018',
    department: 'Engineering',
    dob: '14/02/1997',
    street: 'Estreet',
    city: 'Dcity',
    state: 'E',
    zipCode: '05'
  },
  {
    firstName: 'TestEmployee5',
    lastName: 'Five',
    startDate: '05/12/2022',
    department: 'Legal',
    dob: '10/09/1999',
    street: 'Fstreet',
    city: 'Ecity',
    state: 'F',
    zipCode: '06'
  },{
    firstName: 'TestEmployee1',
    lastName: 'One',
    startDate: '01/01/2020',
    department: 'Human Resources',
    dob: '31/01/2000',
    street: 'Bstreet',
    city: 'Asity',
    state: 'B',
    zipCode: '02'
  },
  {
    firstName: 'TestEmployee2',
    lastName: 'Two',
    startDate: '15/03/2021',
    department: 'Sales',
    dob: '12/06/1998',
    street: 'Cstreet',
    city: 'Bcity',
    state: 'C',
    zipCode: '03'
  },
  {
    firstName: 'TestEmployee3',
    lastName: 'Three',
    startDate: '22/07/2019',
    department: 'Marketing',
    dob: '23/11/1995',
    street: 'Dstreet',
    city: 'Ccity',
    state: 'D',
    zipCode: '04'
  },
  {
    firstName: 'TestEmployee4',
    lastName: 'Four',
    startDate: '30/08/2018',
    department: 'Engineering',
    dob: '14/02/1997',
    street: 'Estreet',
    city: 'Dcity',
    state: 'E',
    zipCode: '05'
  },
  {
    firstName: 'TestEmployee5',
    lastName: 'Five',
    startDate: '05/12/2022',
    department: 'Legal',
    dob: '10/09/1999',
    street: 'Fstreet',
    city: 'Ecity',
    state: 'F',
    zipCode: '06'
  },{
    firstName: 'TestEmployee1',
    lastName: 'One',
    startDate: '01/01/2020',
    department: 'Human Resources',
    dob: '31/01/2000',
    street: 'Bstreet',
    city: 'Asity',
    state: 'B',
    zipCode: '02'
  },
  {
    firstName: 'TestEmployee2',
    lastName: 'Two',
    startDate: '15/03/2021',
    department: 'Sales',
    dob: '12/06/1998',
    street: 'Cstreet',
    city: 'Bcity',
    state: 'C',
    zipCode: '03'
  },
  {
    firstName: 'TestEmployee3',
    lastName: 'Three',
    startDate: '22/07/2019',
    department: 'Marketing',
    dob: '23/11/1995',
    street: 'Dstreet',
    city: 'Ccity',
    state: 'D',
    zipCode: '04'
  },
  {
    firstName: 'TestEmployee4',
    lastName: 'Four',
    startDate: '30/08/2018',
    department: 'Engineering',
    dob: '14/02/1997',
    street: 'Estreet',
    city: 'Dcity',
    state: 'E',
    zipCode: '05'
  },
  {
    firstName: 'TestEmployee5',
    lastName: 'Five',
    startDate: '05/12/2022',
    department: 'Legal',
    dob: '10/09/1999',
    street: 'Fstreet',
    city: 'Ecity',
    state: 'F',
    zipCode: '06'
  },{
    firstName: 'TestEmployee1',
    lastName: 'One',
    startDate: '01/01/2020',
    department: 'Human Resources',
    dob: '31/01/2000',
    street: 'Bstreet',
    city: 'Asity',
    state: 'B',
    zipCode: '02'
  },
  {
    firstName: 'TestEmployee2',
    lastName: 'Two',
    startDate: '15/03/2021',
    department: 'Sales',
    dob: '12/06/1998',
    street: 'Cstreet',
    city: 'Bcity',
    state: 'C',
    zipCode: '03'
  },
  {
    firstName: 'TestEmployee3',
    lastName: 'Three',
    startDate: '22/07/2019',
    department: 'Marketing',
    dob: '23/11/1995',
    street: 'Dstreet',
    city: 'Ccity',
    state: 'D',
    zipCode: '04'
  },
  {
    firstName: 'TestEmployee4',
    lastName: 'Four',
    startDate: '30/08/2018',
    department: 'Engineering',
    dob: '14/02/1997',
    street: 'Estreet',
    city: 'Dcity',
    state: 'E',
    zipCode: '05'
  },
  {
    firstName: 'TestEmployee5',
    lastName: 'Five',
    startDate: '05/12/2022',
    department: 'Legal',
    dob: '10/09/1999',
    street: 'Fstreet',
    city: 'Ecity',
    state: 'F',
    zipCode: '06'
  },{
    firstName: 'TestEmployee1',
    lastName: 'One',
    startDate: '01/01/2020',
    department: 'Human Resources',
    dob: '31/01/2000',
    street: 'Bstreet',
    city: 'Asity',
    state: 'B',
    zipCode: '02'
  },
  {
    firstName: 'TestEmployee2',
    lastName: 'Two',
    startDate: '15/03/2021',
    department: 'Sales',
    dob: '12/06/1998',
    street: 'Cstreet',
    city: 'Bcity',
    state: 'C',
    zipCode: '03'
  },
  {
    firstName: 'TestEmployee3',
    lastName: 'Three',
    startDate: '22/07/2019',
    department: 'Marketing',
    dob: '23/11/1995',
    street: 'Dstreet',
    city: 'Ccity',
    state: 'D',
    zipCode: '04'
  },
  {
    firstName: 'TestEmployee4',
    lastName: 'Four',
    startDate: '30/08/2018',
    department: 'Engineering',
    dob: '14/02/1997',
    street: 'Estreet',
    city: 'Dcity',
    state: 'E',
    zipCode: '05'
  },
  {
    firstName: 'TestEmployee5',
    lastName: 'Five',
    startDate: '05/12/2022',
    department: 'Legal',
    dob: '10/09/1999',
    street: 'Fstreet',
    city: 'Ecity',
    state: 'F',
    zipCode: '06'
  },{
    firstName: 'TestEmployee1',
    lastName: 'One',
    startDate: '01/01/2020',
    department: 'Human Resources',
    dob: '31/01/2000',
    street: 'Bstreet',
    city: 'Asity',
    state: 'B',
    zipCode: '02'
  },
  {
    firstName: 'TestEmployee2',
    lastName: 'Two',
    startDate: '15/03/2021',
    department: 'Sales',
    dob: '12/06/1998',
    street: 'Cstreet',
    city: 'Bcity',
    state: 'C',
    zipCode: '03'
  },
  {
    firstName: 'TestEmployee3',
    lastName: 'Three',
    startDate: '22/07/2019',
    department: 'Marketing',
    dob: '23/11/1995',
    street: 'Dstreet',
    city: 'Ccity',
    state: 'D',
    zipCode: '04'
  },
  {
    firstName: 'TestEmployee4',
    lastName: 'Four',
    startDate: '30/08/2018',
    department: 'Engineering',
    dob: '14/02/1997',
    street: 'Estreet',
    city: 'Dcity',
    state: 'E',
    zipCode: '05'
  },
  {
    firstName: 'TestEmployee5',
    lastName: 'Five',
    startDate: '05/12/2022',
    department: 'Legal',
    dob: '10/09/1999',
    street: 'Fstreet',
    city: 'Ecity',
    state: 'F',
    zipCode: '06'
  },
  {
    firstName: 'TestEmployee1',
    lastName: 'One',
    startDate: '01/01/2020',
    department: 'Human Resources',
    dob: '31/01/2000',
    street: 'Bstreet',
    city: 'Asity',
    state: 'B',
    zipCode: '02'
  },
  {
    firstName: 'TestEmployee2',
    lastName: 'Two',
    startDate: '15/03/2021',
    department: 'Sales',
    dob: '12/06/1998',
    street: 'Cstreet',
    city: 'Bcity',
    state: 'C',
    zipCode: '03'
  },
  {
    firstName: 'TestEmployee3',
    lastName: 'Three',
    startDate: '22/07/2019',
    department: 'Marketing',
    dob: '23/11/1995',
    street: 'Dstreet',
    city: 'Ccity',
    state: 'D',
    zipCode: '04'
  },
  {
    firstName: 'TestEmployee4',
    lastName: 'Four',
    startDate: '30/08/2018',
    department: 'Engineering',
    dob: '14/02/1997',
    street: 'Estreet',
    city: 'Dcity',
    state: 'E',
    zipCode: '05'
  },
  {
    firstName: 'TestEmployee5',
    lastName: 'Five',
    startDate: '05/12/2022',
    department: 'Legal',
    dob: '10/09/1999',
    street: 'Fstreet',
    city: 'Ecity',
    state: 'F',
    zipCode: '06'
  },{
    firstName: 'TestEmployee1',
    lastName: 'One',
    startDate: '01/01/2020',
    department: 'Human Resources',
    dob: '31/01/2000',
    street: 'Bstreet',
    city: 'Asity',
    state: 'B',
    zipCode: '02'
  },
  {
    firstName: 'TestEmployee2',
    lastName: 'Two',
    startDate: '15/03/2021',
    department: 'Sales',
    dob: '12/06/1998',
    street: 'Cstreet',
    city: 'Bcity',
    state: 'C',
    zipCode: '03'
  },
  {
    firstName: 'TestEmployee3',
    lastName: 'Three',
    startDate: '22/07/2019',
    department: 'Marketing',
    dob: '23/11/1995',
    street: 'Dstreet',
    city: 'Ccity',
    state: 'D',
    zipCode: '04'
  },
  {
    firstName: 'TestEmployee4',
    lastName: 'Four',
    startDate: '30/08/2018',
    department: 'Engineering',
    dob: '14/02/1997',
    street: 'Estreet',
    city: 'Dcity',
    state: 'E',
    zipCode: '05'
  },
  {
    firstName: 'TestEmployee5',
    lastName: 'Five',
    startDate: '05/12/2022',
    department: 'Legal',
    dob: '10/09/1999',
    street: 'Fstreet',
    city: 'Ecity',
    state: 'F',
    zipCode: '06'
  },{
    firstName: 'TestEmployee1',
    lastName: 'One',
    startDate: '01/01/2020',
    department: 'Human Resources',
    dob: '31/01/2000',
    street: 'Bstreet',
    city: 'Asity',
    state: 'B',
    zipCode: '02'
  },
  {
    firstName: 'TestEmployee2',
    lastName: 'Two',
    startDate: '15/03/2021',
    department: 'Sales',
    dob: '12/06/1998',
    street: 'Cstreet',
    city: 'Bcity',
    state: 'C',
    zipCode: '03'
  },
  {
    firstName: 'TestEmployee3',
    lastName: 'Three',
    startDate: '22/07/2019',
    department: 'Marketing',
    dob: '23/11/1995',
    street: 'Dstreet',
    city: 'Ccity',
    state: 'D',
    zipCode: '04'
  },
  {
    firstName: 'TestEmployee4',
    lastName: 'Four',
    startDate: '30/08/2018',
    department: 'Engineering',
    dob: '14/02/1997',
    street: 'Estreet',
    city: 'Dcity',
    state: 'E',
    zipCode: '05'
  },
  {
    firstName: 'TestEmployee5',
    lastName: 'Five',
    startDate: '05/12/2022',
    department: 'Legal',
    dob: '10/09/1999',
    street: 'Fstreet',
    city: 'Ecity',
    state: 'F',
    zipCode: '06'
  },{
    firstName: 'TestEmployee1',
    lastName: 'One',
    startDate: '01/01/2020',
    department: 'Human Resources',
    dob: '31/01/2000',
    street: 'Bstreet',
    city: 'Asity',
    state: 'B',
    zipCode: '02'
  },
  {
    firstName: 'TestEmployee2',
    lastName: 'Two',
    startDate: '15/03/2021',
    department: 'Sales',
    dob: '12/06/1998',
    street: 'Cstreet',
    city: 'Bcity',
    state: 'C',
    zipCode: '03'
  },
  {
    firstName: 'TestEmployee3',
    lastName: 'Three',
    startDate: '22/07/2019',
    department: 'Marketing',
    dob: '23/11/1995',
    street: 'Dstreet',
    city: 'Ccity',
    state: 'D',
    zipCode: '04'
  },
  {
    firstName: 'TestEmployee4',
    lastName: 'Four',
    startDate: '30/08/2018',
    department: 'Engineering',
    dob: '14/02/1997',
    street: 'Estreet',
    city: 'Dcity',
    state: 'E',
    zipCode: '05'
  },
  {
    firstName: 'TestEmployee5',
    lastName: 'Five',
    startDate: '05/12/2022',
    department: 'Legal',
    dob: '10/09/1999',
    street: 'Fstreet',
    city: 'Ecity',
    state: 'F',
    zipCode: '06'
  },{
    firstName: 'TestEmployee1',
    lastName: 'One',
    startDate: '01/01/2020',
    department: 'Human Resources',
    dob: '31/01/2000',
    street: 'Bstreet',
    city: 'Asity',
    state: 'B',
    zipCode: '02'
  },
  {
    firstName: 'TestEmployee2',
    lastName: 'Two',
    startDate: '15/03/2021',
    department: 'Sales',
    dob: '12/06/1998',
    street: 'Cstreet',
    city: 'Bcity',
    state: 'C',
    zipCode: '03'
  },
  {
    firstName: 'TestEmployee3',
    lastName: 'Three',
    startDate: '22/07/2019',
    department: 'Marketing',
    dob: '23/11/1995',
    street: 'Dstreet',
    city: 'Ccity',
    state: 'D',
    zipCode: '04'
  },
  {
    firstName: 'TestEmployee4',
    lastName: 'Four',
    startDate: '30/08/2018',
    department: 'Engineering',
    dob: '14/02/1997',
    street: 'Estreet',
    city: 'Dcity',
    state: 'E',
    zipCode: '05'
  },
  {
    firstName: 'TestEmployee5',
    lastName: 'Five',
    startDate: '05/12/2022',
    department: 'Legal',
    dob: '10/09/1999',
    street: 'Fstreet',
    city: 'Ecity',
    state: 'F',
    zipCode: '06'
  },{
    firstName: 'TestEmployee1',
    lastName: 'One',
    startDate: '01/01/2020',
    department: 'Human Resources',
    dob: '31/01/2000',
    street: 'Bstreet',
    city: 'Asity',
    state: 'B',
    zipCode: '02'
  },
  {
    firstName: 'TestEmployee2',
    lastName: 'Two',
    startDate: '15/03/2021',
    department: 'Sales',
    dob: '12/06/1998',
    street: 'Cstreet',
    city: 'Bcity',
    state: 'C',
    zipCode: '03'
  },
  {
    firstName: 'TestEmployee3',
    lastName: 'Three',
    startDate: '22/07/2019',
    department: 'Marketing',
    dob: '23/11/1995',
    street: 'Dstreet',
    city: 'Ccity',
    state: 'D',
    zipCode: '04'
  },
  {
    firstName: 'TestEmployee4',
    lastName: 'Four',
    startDate: '30/08/2018',
    department: 'Engineering',
    dob: '14/02/1997',
    street: 'Estreet',
    city: 'Dcity',
    state: 'E',
    zipCode: '05'
  },
  {
    firstName: 'TestEmployee5',
    lastName: 'Five',
    startDate: '05/12/2022',
    department: 'Legal',
    dob: '10/09/1999',
    street: 'Fstreet',
    city: 'Ecity',
    state: 'F',
    zipCode: '06'
  },{
    firstName: 'TestEmployee1',
    lastName: 'One',
    startDate: '01/01/2020',
    department: 'Human Resources',
    dob: '31/01/2000',
    street: 'Bstreet',
    city: 'Asity',
    state: 'B',
    zipCode: '02'
  },
  {
    firstName: 'TestEmployee2',
    lastName: 'Two',
    startDate: '15/03/2021',
    department: 'Sales',
    dob: '12/06/1998',
    street: 'Cstreet',
    city: 'Bcity',
    state: 'C',
    zipCode: '03'
  },
  {
    firstName: 'TestEmployee3',
    lastName: 'Three',
    startDate: '22/07/2019',
    department: 'Marketing',
    dob: '23/11/1995',
    street: 'Dstreet',
    city: 'Ccity',
    state: 'D',
    zipCode: '04'
  },
  {
    firstName: 'TestEmployee4',
    lastName: 'Four',
    startDate: '30/08/2018',
    department: 'Engineering',
    dob: '14/02/1997',
    street: 'Estreet',
    city: 'Dcity',
    state: 'E',
    zipCode: '05'
  },
  {
    firstName: 'TestEmployee5',
    lastName: 'Five',
    startDate: '05/12/2022',
    department: 'Legal',
    dob: '10/09/1999',
    street: 'Fstreet',
    city: 'Ecity',
    state: 'F',
    zipCode: '06'
  },{
    firstName: 'TestEmployee1',
    lastName: 'One',
    startDate: '01/01/2020',
    department: 'Human Resources',
    dob: '31/01/2000',
    street: 'Bstreet',
    city: 'Asity',
    state: 'B',
    zipCode: '02'
  },
  {
    firstName: 'TestEmployee2',
    lastName: 'Two',
    startDate: '15/03/2021',
    department: 'Sales',
    dob: '12/06/1998',
    street: 'Cstreet',
    city: 'Bcity',
    state: 'C',
    zipCode: '03'
  },
  {
    firstName: 'TestEmployee3',
    lastName: 'Three',
    startDate: '22/07/2019',
    department: 'Marketing',
    dob: '23/11/1995',
    street: 'Dstreet',
    city: 'Ccity',
    state: 'D',
    zipCode: '04'
  },
  {
    firstName: 'TestEmployee4',
    lastName: 'Four',
    startDate: '30/08/2018',
    department: 'Engineering',
    dob: '14/02/1997',
    street: 'Estreet',
    city: 'Dcity',
    state: 'E',
    zipCode: '05'
  },
  {
    firstName: 'TestEmployee5',
    lastName: 'Five',
    startDate: '05/12/2022',
    department: 'Legal',
    dob: '10/09/1999',
    street: 'Fstreet',
    city: 'Ecity',
    state: 'F',
    zipCode: '06'
  }


];


